services:
  bandsos:
    image: jamal919/bandsos
    container_name: bandsos
    restart: always
    shm_size: '512mb'     # Necessary for running SCHISM
    dns:                  # The DNS fix for Herbie/S3 resolution
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - bandsos.env
    volumes:
      - ~/.gitconfig:/etc/gitconfig
      - .:/mnt
      - /tmp:/tmp
    user: "${UID}:${GID}" # Running as your current user; create a .env file with these fields
    command: python run_bandsos.py
    labels:
      - "com.containrrr.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400 # Checking every day
